<a href="https://colab.research.google.com/github/avseksingh/DataSciencePractice/blob/main/reshaping_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Create the array and print the array and its shape

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


reshape it

In [5]:
a = a.reshape(4,3) # 4x3
print(a, type(a))
print(a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] <class 'numpy.ndarray'>
(4, 3)


In [6]:
a = a.reshape(2,3,2)#2x3x2
print(a, type(a))
print(a.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] <class 'numpy.ndarray'>
(2, 3, 2)


In [7]:
a = a.reshape(1,12)#1x12
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)


Reshape it using Negativ indexes

In [9]:
a = a.reshape(-2,3)#4x3
print(a)
print(a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [10]:
a = a.reshape(2,3,-2) #2x3x2
print(a)
print(a.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [12]:
a = a.reshape(1,-1) # 12 x 1
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)


In [13]:
a = a.reshape(12,-1) # 1x 12
print(a)
print(a.shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
(12, 1)
