<a href="https://colab.research.google.com/github/avseksingh/DataSciencePractice/blob/main/starting%20numpy%20arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
a = np.array((1,2,3,4,5))
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
a =  np.array({1,2,3,4,5})
print(a)
print(type(a))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


In [6]:
a = np.array({"One":1,"Two":2,"Three":3,"Four":4,"Five":5})
print(a)
print(type(a))


{'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}
<class 'numpy.ndarray'>


In [9]:
a = np.array(range(1,6))
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
a = np.ones(5)
print(a, type(a))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [11]:
a = np.zeros(5)
print(a, type(a))

[0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


Create an array using arange

In [13]:
a = np.arange(5)
print(a)
a = np.arange(1,6)
print(a)
a = np.arange(1,6,2)
print(a)
a = np.arange(5,0,-1)
print(a)


[0 1 2 3 4]
[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]


Create an array using random

In [26]:
# a = np.random.rand(10,15)
# print(a)
# a = np.random.power(5,5)
# print(a)
# a = np.random.randint(5,size=5)
# print(a)
rng = np.random.default_rng()
a = rng.integers(5,size=5)
print(a)

[0 0 4 2 0]
